export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_REPORTS = 'FETCH_REPORTS';
export const FETCH_USERS = 'FETCH_USERS';
export const EDIT_USER = 'EDIT_USER';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const NEW_POST = 'NEW_POST';
export const SUCCESSFULY_REGISTERED = 'SUCCESSFULY_REGISTERED';
export const I_AM_A_TEAPOT = 'I_AM_A_TEAPOT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SUCCESS_EDIT_REPORT = 'SUCCESS_EDIT_REPORT';
export const CANCEL_EDIT_REPORT = 'CANCEL_EDIT_REPORT';
export const FETCH_OVERVIEW_REPORTS = 'FETCH_OVERVIEW_REPORTS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

